'''
Dario Sanai
sanai_dario_dariush@student.smc.edu
CS87A, Fall 2024
Music Lab
'''

import soundLib
import scipy
import numpy
import pyaudio
import wave

soundLib.initSound()

soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)

soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)

soundLib.addNote("D5", 1)
soundLib.addNote("D5", 1)
soundLib.addNote("D5", 1)
soundLib.addNote("D5", 1)

soundLib.addNote("C5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("C5", 1)

soundLib.addNote("F5", 1)
soundLib.addNote("F5", 1)
soundLib.addNote("F5", 1)
soundLib.addNote("F5", 1)

soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)

soundLib.addNote("C5", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("A5", 1)
soundLib.addNote("F4", 1)

soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("D5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("B5flat", 1)

soundLib.addNote("A5", 1)
soundLib.addNote("A5", 1)
soundLib.addNote("A5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("A5", 1)

soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("B6flat", 1)
soundLib.addNote("A6", 1)
soundLib.addNote("B6flat", 1)
soundLib.addNote("A6", 1)
soundLib.addNote("B6flat", 1)

soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("B6flat", 1)
soundLib.addNote("A6", 1)
soundLib.addNote("B6flat", 1)
soundLib.addNote("A6", 1)
soundLib.addNote("B6flat", 1)

soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("D5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("B5flat", 1)

soundLib.addNote("A5", 1)
soundLib.addNote("A5", 1)
soundLib.addNote("A5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("A5", 1)

soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("B6flat", 1)
soundLib.addNote("A6", 1)
soundLib.addNote("B6flat", 1)
soundLib.addNote("A6", 1)
soundLib.addNote("B6flat", 1)

soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("B6flat", 1)
soundLib.addNote("A6", 1)
soundLib.addNote("B6flat", 1)
soundLib.addNote("A6", 1)
soundLib.addNote("B6flat", 1)

soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("D5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("B5flat", 1)

soundLib.addNote("A5", 1)
soundLib.addNote("A5", 1)
soundLib.addNote("A5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("A5", 1)

soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("B6flat", 1)
soundLib.addNote("A6", 1)
soundLib.addNote("B6flat", 1)
soundLib.addNote("A6", 1)
soundLib.addNote("B6flat", 1)

soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("B6flat", 1)
soundLib.addNote("A6", 1)
soundLib.addNote("B6flat", 1)
soundLib.addNote("A6", 1)
soundLib.addNote("B6flat", 1)

soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("D5", 1)
soundLib.addNote("D5", 1)
soundLib.addNote("D5", 1)
soundLib.addNote("D5", 1)

soundLib.addNote("C5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("F5", 1)
soundLib.addNote("F5", 1)
soundLib.addNote("F5", 1)
soundLib.addNote("F5", 1)

soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)
soundLib.addNote("G5", 1)

soundLib.addNote("C5", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("A5", 1)
soundLib.addNote("F4", 1)

soundLib.addNote("G4", 1)
soundLib.addNote("G4", 1)
soundLib.addNote("D5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("B5flat", 1)

soundLib.addNote("A5", 1)
soundLib.addNote("A5", 1)
soundLib.addNote("A5", 1)
soundLib.addNote("C5", 1)
soundLib.addNote("B5flat", 1)
soundLib.addNote("A5", 1)


soundLib.playSound()
